import { useState } from 'react'
import type { ImplementedExercise } from '../../domain/exercise'
import type { Part2Exercise } from '../../domain/part2'
import type { Part3Exercise } from '../../domain/part3'
import type { Part4Exercise } from '../../domain/part4'
import { gradeExercise, type ExerciseGrade } from '../../grading'
import { submitExerciseAttempt } from '../../application/attemptSubmission'

interface Props { exercise: Part2Exercise | Part3Exercise | Part4Exercise; onBack: () => void }
function newKey(part: number) { return `${part}-${typeof crypto !== 'undefined' && crypto.randomUUID ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`}` }
function passage(text: string) { return text.split(/(\{\{gap:\d+\}\})/gu).map((part, index) => { const gap = part.match(/\{\{gap:(\d+)\}\}/u); return gap ? <span key={index}>({gap[1]}) ______</span> : <span key={index}>{part}</span> }) }
export default function TextExercisePage({ exercise, onBack }: Props) {
  const [answers, setAnswers] = useState<Record<string, string>>({}); const [grade, setGrade] = useState<ExerciseGrade | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null)
  const submit = async () => { if (saving) return; setSaving(true); setError(null); try { const result = await submitExerciseAttempt({ exercise, answers, idempotencyKey: newKey(exercise.part) }); setGrade(result.grade) } catch { setError('The attempt could not be saved locally. Check that site storage is enabled and try again. Your answer has not been counted.') } finally { setSaving(false) } }
  if (grade) return <section className="part1-shell" aria-labelledby="text-results-title"><div className="part1-heading"><p className="eyebrow">Reading &amp; Use of English · Part {exercise.part}</p><h1 id="text-results-title">Results</h1><p className="part1-score">Score: {grade.score} / {grade.maxScore}</p></div><ol className="part1-results-list">{exercise.questions.map((question, index) => { const result = grade.results[index] as { answer?: string | null; correct: boolean; marks: number; maxMarks?: number; canonicalAnswer?: string; root?: string }; return <li className={`part1-result-card ${result.correct ? 'is-correct' : 'is-incorrect'}`} key={question.id}><div className="part1-result-heading"><h2>Question {index + 1}</h2><strong>{exercise.part === 4 ? `${result.marks}/${result.maxMarks ?? 2} marks` : result.correct ? 'Correct' : 'Incorrect'}</strong></div><p><span className="part1-result-label">Your answer:</span> {result.answer ?? 'Not answered'}</p><p><span className="part1-result-label">Correct answer:</span> {result.canonicalAnswer}</p>{exercise.part === 3 && <p><span className="part1-result-label">Root:</span> {result.root}</p>}<p><span className="part1-result-label">Explanation:</span> {(question as { explanation: string }).explanation}</p></li> })}</ol><div className="part1-actions"><button className="part1-primary-button" type="button" onClick={() => setGrade(null)}>Try again</button><button type="button" onClick={onBack}>Back to practice</button></div></section>
  const setAnswer = (id: string, value: string) => setAnswers((current) => ({ ...current, [id]: value }))
  return <section className="part1-shell" aria-labelledby="text-exercise-title"><div className="part1-toolbar"><button type="button" onClick={onBack}>← Back to practice</button><span className="part1-progress">{exercise.questions.length} questions · {exercise.part === 4 ? '2 marks each' : '1 mark each'}</span></div><div className="part1-heading"><p className="eyebrow">Reading &amp; Use of English · Part {exercise.part}</p><h1 id="text-exercise-title">{exercise.title}</h1><p className="part1-instruction">{exercise.part === 2 ? 'For questions 1–8, read the text and write one word in each gap.' : exercise.part === 3 ? 'For questions 1–8, use the word given in capitals to form a word that fits the gap.' : 'For questions 1–6, complete the second sentence so that it has a similar meaning to the first sentence.'}</p></div>{exercise.part !== 4 && <article className="part1-passage" aria-label="Exercise text"><p>{passage(exercise.content.text)}</p></article>}<form onSubmit={(event) => { event.preventDefault(); void submit() }}><ol className="part1-question-list">{exercise.questions.map((question, index) => <li className="part1-question" key={question.id}>{exercise.part === 4 ? <><p><strong>{(question as any).originalSentence}</strong></p><p>{(question as any).secondSentence.split('{{answer}}').map((part: string, i: number) => <span key={i}>{i ? <input aria-label={`Answer for question ${index + 1}`} value={answers[question.id] ?? ''} onChange={(event) => setAnswer(question.id, event.target.value)} autoCorrect="off" spellCheck={false} /> : null}{part}</span>)}</p><small>Keyword: {(question as any).keyword} · 3–6 words</small></> : <label htmlFor={`answer-${question.id}`}>{exercise.part === 3 && <><strong>{(question as any).root}</strong> — </>}Answer for question {index + 1}<input id={`answer-${question.id}`} value={answers[question.id] ?? ''} onChange={(event) => setAnswer(question.id, event.target.value)} autoCorrect="off" spellCheck={false} /></label>}</li>)}</ol><div className="part1-submit-panel"><button className="part1-primary-button" type="submit" disabled={saving}>{saving ? 'Saving locally…' : 'Submit answers'}</button></div>{error && <p className="part1-submission-error" role="alert">{error}</p>}</form></section>
}
