import type { ErrorBankRecord } from '../../learning'
import { getApprovedPart1Exercise, getApprovedPart2Exercise, getApprovedPart3Exercise, getApprovedPart4Exercise, getApprovedPart5Exercise, getApprovedPart6Exercise, getApprovedPart7Exercise, getApprovedPart8Exercise } from '../../content'
export interface ReviewPrompt { questionText:string; correctText:string; explanation:string; sourceAttemptId?:string; keyword?:string; originalSentence?:string; secondSentence?:string }
export function getReviewPrompt(record: ErrorBankRecord): ReviewPrompt | undefined {
  const exercise = record.part===1?getApprovedPart1Exercise(record.exerciseId):record.part===2?getApprovedPart2Exercise(record.exerciseId):record.part===3?getApprovedPart3Exercise(record.exerciseId):record.part===4?getApprovedPart4Exercise(record.exerciseId):record.part===5?getApprovedPart5Exercise(record.exerciseId):record.part===6?getApprovedPart6Exercise(record.exerciseId):record.part===7?getApprovedPart7Exercise(record.exerciseId):getApprovedPart8Exercise(record.exerciseId)
  const question=exercise?.questions.find(item=>item.id===record.questionId)
  if(!exercise||!question) return record.canonicalAnswer?{questionText:record.prompt??record.contextSnapshot??`${record.part} · ${record.questionId}`,correctText:record.correctTargetLabel??record.canonicalAnswer,explanation:record.explanationReference}:undefined
  if(record.part===1){const item=question as import('../../domain/part1').Part1Question;const ex=exercise as import('../../domain/part1').Part1Exercise;const source=ex.content.text.split(/(?<=[.!?])\s+/u).find((sentence:string)=>sentence.includes(`{{gap:${item.gap}}}`))??ex.content.text;return {questionText:source.replace(`{{gap:${item.gap}}}`,'______').replace(/\{\{gap:\d+\}\}/gu,'…'),correctText:item.options.find(o=>o.id===item.correctOptionId)?.text??item.correctOptionId,explanation:item.explanation}}
  if(record.part===4){const item=question as import('../../domain/part4').Part4Question;return {questionText:`${item.originalSentence}\n${item.secondSentence.replace('{{answer}}','______')}`,correctText:item.canonicalAnswer,explanation:'Rebuild the meaning using the fixed keyword and compare the complete transformation.',keyword:item.keyword,originalSentence:item.originalSentence,secondSentence:item.secondSentence}}
  if(record.part===2||record.part===3){const item=question as import('../../domain/part2').Part2Question|import('../../domain/part3').Part3Question;const ex=exercise as import('../../domain/part2').Part2Exercise|import('../../domain/part3').Part3Exercise;return {questionText:ex.content.text.replace(`{{gap:${item.gap}}}`,'______').replace(/\{\{gap:\d+\}\}/gu,'…'),correctText:item.canonicalAnswer,explanation:item.explanation}}
  const item=question as {prompt:string;explanation:string}; return {questionText:`${item.prompt}${record.contextSnapshot?`\n\nContext: ${record.contextSnapshot}`:''}`,correctText:record.correctTargetLabel??record.canonicalAnswer,explanation:item.explanation}
}
export const getPart1ReviewPrompt=getReviewPrompt
