import { useState } from 'react'
import type { Part5Exercise } from '../../domain/part5'
import { submitExerciseAttempt } from '../../application/attemptSubmission'
import './part5.css'
import '../reading/reading.css'
export default function Part5ExercisePage({ exercise, onBack }: { exercise: Part5Exercise; onBack: () => void }) {
  const [answers, setAnswers] = useState<Record<string, string>>({}); const [grade, setGrade] = useState<any>(null); const [saving, setSaving] = useState(false)
  async function submit() { if(saving)return; setSaving(true); try { setGrade((await submitExerciseAttempt({ exercise, answers, idempotencyKey:`part5:${exercise.id}:${Date.now()}` })).grade) } finally { setSaving(false) } }
  if(grade) return <section className="reading-shell" aria-labelledby="p5-results"><div className="part1-heading"><p className="eyebrow">Reading · Part 5</p><h1 id="p5-results">{exercise.title}</h1><p className="part1-score">Score: {grade.score} / {grade.maxScore}</p></div><ol className="reading-results">{exercise.questions.map((q,i)=>{const r=grade.results[i]; const correct=q.options.find(o=>o.id===q.correctOptionId); return <li className={`reading-result ${r.correct?'is-correct':''}`} key={q.id}><strong>Question {i+1} · {r.correct?'Correct':'Incorrect'}</strong><p>Your answer: {r.selectedOptionId??'Not answered'}</p><p>Correct answer: {q.correctOptionId} — {correct?.text}</p><p>{q.explanation}</p></li>})}</ol><div className="reading-submit"><button className="reading-primary" onClick={()=>setGrade(null)}>Try again</button><button onClick={onBack}>Back to reading</button></div></section>
  return <section className="reading-shell" aria-labelledby="p5-title"><div className="reading-toolbar"><button onClick={onBack}>← Back</button><span>6 questions · 2 marks each</span></div><div className="part1-heading"><p className="eyebrow">Cambridge C1 Advanced · Reading Part 5</p><h1 id="p5-title">{exercise.title}</h1><p className="part1-instruction">Read the text and choose the best answer for each question.</p></div><div className="reading-layout"><article className="reading-text">{exercise.content.text}</article><form className="reading-card" onSubmit={e=>{e.preventDefault();void submit()}}><ol className="reading-questions">{exercise.questions.map((q,i)=><li className="reading-question" key={q.id}><fieldset><legend>{i+1}. {q.prompt}</legend><div className="reading-options">{q.options.map(o=><label className="reading-option" key={o.id}><input type="radio" name={q.id} value={o.id} checked={answers[q.id]===o.id} onChange={()=>setAnswers(a=>({...a,[q.id]:o.id}))}/><span><strong>{o.id}</strong> {o.text}</span></label>)}</div></fieldset></li>)}</ol><button className="reading-primary" disabled={saving}>{saving?'Saving…':'Submit answers'}</button></form></div></section>
}
