export {
  getApprovedPart1Exercise,
  getApprovedPart2Exercise,
  getApprovedPart3Exercise,
  getApprovedPart4Exercise,
  getApprovedPart5Exercise,
  getApprovedPart6Exercise,
  getApprovedPart7Exercise,
  getApprovedPart8Exercise,
  listApprovedExercises,
  listApprovedPart1Exercises,
  listApprovedPart2Exercises,
  listApprovedPart3Exercises,
  listApprovedPart4Exercises,
  listApprovedPart5Exercises,
  listApprovedPart6Exercises,
  listApprovedPart7Exercises,
  listApprovedPart8Exercises,
} from './contentRepository'
